#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 VERSION" >&2
	exit 1
fi

ARCH=$(go env GOARCH)
OS=$(go env GOOS)
DOCKERFILE="Dockerfile-release"
TAG="quay.io/philips/backplane"

if [ -z ${BINARYDIR} ]; then
	RELEASE="backplane-${1}-${OS}-${ARCH}"
	BINARYDIR="${RELEASE}"
	TARFILE="${RELEASE}.tar.gz"
	
	TARURL="https://bin.equinox.io/c/jWahGASjoRq/$RELEASE.tgz"
	curl -f -L -o ${TARFILE} ${TARURL}
	if [ $? != 0 ]; then
		echo "Failed to download ${TARURL}."
		exit 1
	fi
	tar -zvxf ${TARFILE}
fi

if [ ${ARCH} != "amd64" ]; then
	DOCKERFILE+=".${ARCH}"
	TAG+="-${ARCH}"
fi

BINARYDIR=${BINARYDIR:-.}
BUILDDIR=${BUILDDIR:-.}

IMAGEDIR=${BUILDDIR}/image-docker

mkdir -p ${IMAGEDIR}
cp backplane ${IMAGEDIR}

cat ./${DOCKERFILE} > ${IMAGEDIR}/Dockerfile

docker build -t ${TAG}:${1} ${IMAGEDIR}
